import { WorkspacePage } from "@/components/WorkspacePage";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { ImagePlus, Loader2, Sparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function ImageGeneration() {
  const utils = trpc.useUtils(); const [prompt, setPrompt] = useState("");
  const images = trpc.images.list.useQuery();
  const generate = trpc.images.generate.useMutation({ onSuccess: async () => { setPrompt(""); await Promise.all([utils.images.list.invalidate(), utils.workspace.summary.invalidate(), utils.taskHistory.list.invalidate()]); toast.success("Your image is ready in the gallery."); }, onError: error => toast.error(error.message) });
  return <WorkspacePage eyebrow="Visual studio" title="Image Generation" description="Translate a clear creative direction into polished visuals, then keep every result in a private, searchable gallery.">
    <section className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]"><div className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex size-10 items-center justify-center rounded-xl bg-primary/15 text-primary"><ImagePlus className="size-5" /></div><h2 className="mt-5 font-semibold tracking-tight">Describe the image you want</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Include subject, style, composition, lighting, and any visual constraints.</p><Textarea value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="A calm editorial still life of ..." className="mt-5 min-h-40 resize-none rounded-xl bg-background/60" /><Button disabled={generate.isPending || prompt.trim().length < 3} onClick={() => generate.mutate({ prompt: prompt.trim() })} className="mt-3 w-full gap-2 rounded-xl">{generate.isPending ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}{generate.isPending ? "Generating image…" : "Generate image"}</Button><p className="mt-3 text-center text-[11px] leading-4 text-muted-foreground">Generation can take a few seconds. Results are saved only in your workspace.</p></div>
      <div className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex items-center justify-between"><div><h2 className="font-semibold tracking-tight">Your gallery</h2><p className="mt-1 text-sm text-muted-foreground">Recent image outputs.</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium text-muted-foreground">{images.data?.length ?? 0} items</span></div><div className="mt-5 grid max-h-[560px] grid-cols-2 gap-3 overflow-auto pr-1 sm:grid-cols-3">{images.isLoading ? [0, 1, 2].map(index => <div key={index} className="aspect-square animate-pulse rounded-xl bg-muted" />) : images.isError ? <div role="alert" className="col-span-full rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-center text-xs text-destructive">Your gallery could not be loaded. Refresh to try again.</div> : images.data?.map(image => <article key={image.id} className="group overflow-hidden rounded-xl border bg-background/40"><img src={image.imageUrl} alt={image.prompt} className="aspect-square w-full object-cover transition duration-300 group-hover:scale-[1.03]" /><div className="p-2.5"><p className="line-clamp-2 text-xs leading-5 text-foreground/85">{image.prompt}</p><p className="mt-1 text-[10px] text-muted-foreground">{formatDate(image.createdAt)}</p></div></article>)}{!images.isLoading && !images.isError && !images.data?.length && <div className="col-span-full grid min-h-72 place-items-center rounded-xl border border-dashed bg-background/20 p-6 text-center"><div><ImagePlus className="mx-auto size-7 text-muted-foreground/60" /><p className="mt-3 text-sm font-medium">No images yet</p><p className="mt-1 text-xs text-muted-foreground">Your creations will appear here.</p></div></div>}</div></div></section>
  </WorkspacePage>;
}
