import { WorkspacePage } from "@/components/WorkspacePage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { CalendarClock, Loader2, Pause, Play, Plus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function ScheduledTasks() {
  const utils = trpc.useUtils(); const workflows = trpc.workflows.list.useQuery(); const tasks = trpc.scheduledTasks.list.useQuery(); const [workflowId, setWorkflowId] = useState<number | null>(null); const [name, setName] = useState("Daily workflow"); const [cronExpression, setCronExpression] = useState("0 0 9 * * *");
  useEffect(() => { if (!workflowId && workflows.data?.[0]) setWorkflowId(workflows.data[0].id); }, [workflowId, workflows.data]);
  const refresh = async () => { await Promise.all([utils.scheduledTasks.list.invalidate(), utils.workspace.summary.invalidate()]); };
  const create = trpc.scheduledTasks.create.useMutation({ onSuccess: async () => { await refresh(); toast.success("Scheduled task activated."); }, onError: error => toast.error(error.message) });
  const pause = trpc.scheduledTasks.pause.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) }); const resume = trpc.scheduledTasks.resume.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) }); const remove = trpc.scheduledTasks.delete.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const canCreateScheduledTask = import.meta.env.PROD;
  return <WorkspacePage eyebrow="Reliable routines" title="Scheduled Tasks" description="Let a saved workflow run on a recurring UTC schedule. Each job belongs only to the workspace that created it.">
    <div className="rounded-xl border border-amber-300/15 bg-amber-300/5 px-4 py-3 text-xs leading-5 text-amber-100/80">{canCreateScheduledTask ? "Schedule state is synced from the scheduler whenever you open this page." : "Publish the app before creating Scheduled Tasks so secure callbacks are reachable."} Use six cron fields in UTC: seconds, minutes, hours, day-of-month, month, weekday. Example: <span className="font-mono text-amber-100">0 0 9 * * *</span> runs daily at 09:00 UTC.</div>
    <section className="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><div className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex size-10 items-center justify-center rounded-xl bg-primary/15 text-primary"><Plus className="size-5" /></div><h2 className="mt-5 font-semibold tracking-tight">Create a recurring task</h2><Input value={name} onChange={event => setName(event.target.value)} className="mt-4 rounded-xl bg-background/60" placeholder="Task name" /><select value={workflowId ?? ""} onChange={event => setWorkflowId(Number(event.target.value))} disabled={workflows.isLoading || workflows.isError} className="mt-3 h-10 w-full rounded-xl border border-input bg-background/60 px-3 text-sm outline-none focus:ring-2 focus:ring-ring"><option value="" disabled>{workflows.isLoading ? "Loading workflows…" : "Select a workflow"}</option>{workflows.data?.map(workflow => <option key={workflow.id} value={workflow.id}>{workflow.name}</option>)}</select><Input value={cronExpression} onChange={event => setCronExpression(event.target.value)} className="mt-3 rounded-xl bg-background/60 font-mono text-xs" placeholder="0 0 9 * * *" /><Button disabled={!canCreateScheduledTask || !workflowId || create.isPending || name.trim().length < 2} onClick={() => workflowId && create.mutate({ workflowId, name: name.trim(), cronExpression })} className="mt-3 w-full gap-2 rounded-xl">{create.isPending ? <Loader2 className="size-4 animate-spin" /> : <CalendarClock className="size-4" />}{canCreateScheduledTask ? "Create scheduled task" : "Publish to activate scheduling"}</Button>{create.isError && <p role="alert" className="mt-3 text-xs text-destructive">{create.error.message}</p>}{workflows.isError ? <p role="alert" className="mt-3 text-xs text-destructive">Workflows could not be loaded. Refresh to try again.</p> : !workflows.isLoading && !workflows.data?.length && <p className="mt-3 text-xs leading-5 text-muted-foreground">Create a workflow before scheduling it.</p>}</div>
      <div className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex items-center justify-between"><div><h2 className="font-semibold tracking-tight">Your recurring jobs</h2><p className="mt-1 text-sm text-muted-foreground">Pause, resume, or remove your own jobs.</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium text-muted-foreground">{tasks.data?.length ?? 0} tasks</span></div><div className="mt-5 divide-y divide-border/70">{tasks.isLoading ? [0, 1].map(index => <div key={index} className="h-24 animate-pulse rounded-xl bg-muted/60" />) : tasks.isError ? <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-center text-xs text-destructive">Scheduled Tasks could not be loaded. Refresh to try again.</div> : tasks.data?.map(task => <div key={task.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center"><div className="grid size-10 place-items-center rounded-xl bg-muted"><CalendarClock className="size-4 text-primary" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{task.name}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">{task.cronExpression}</p><p className="mt-1 text-[11px] text-muted-foreground">Next: {formatDate(task.nextRunAt)} · Last: {formatDate(task.lastRunAt)}</p></div><div className="flex gap-2">{task.isPaused ? <Button size="sm" variant="outline" onClick={() => resume.mutate({ id: task.id })} className="gap-1.5 rounded-lg"><Play className="size-3.5" /> Resume</Button> : <Button size="sm" variant="outline" onClick={() => pause.mutate({ id: task.id })} className="gap-1.5 rounded-lg"><Pause className="size-3.5" /> Pause</Button>}<Button size="icon" variant="ghost" onClick={() => { if (window.confirm(`Delete “${task.name}”?`)) remove.mutate({ id: task.id }); }} className="size-8 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="size-3.5" /></Button></div></div>)}{!tasks.isLoading && !tasks.isError && !tasks.data?.length && <div className="py-16 text-center"><CalendarClock className="mx-auto size-7 text-muted-foreground/60" /><p className="mt-3 text-sm font-medium">No scheduled tasks yet</p><p className="mt-1 text-xs text-muted-foreground">Create a recurring run from a saved workflow.</p></div>}</div></div>
    </section>
  </WorkspacePage>;
}
