import { WorkspacePage } from "@/components/WorkspacePage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Check, Loader2, PlugZap, Settings2, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export default function Settings() {
  const utils = trpc.useUtils(); const settings = trpc.settings.get.useQuery(); const [defaultModel, setDefaultModel] = useState("Default"); const [timeZone, setTimeZone] = useState("UTC"); const [interfaceDensity, setInterfaceDensity] = useState<"comfortable" | "compact">("comfortable");
  const feedbackPreview = typeof window === "undefined" ? null : new URLSearchParams(window.location.search).get("feedbackPreview");
  const previewPreferencesLoading = feedbackPreview === "preferences-loading";
  const previewPreferencesError = feedbackPreview === "preferences-error";
  useEffect(() => { if (settings.data?.preferences) { setDefaultModel(settings.data.preferences.defaultModel ?? "Default"); setTimeZone(settings.data.preferences.timeZone ?? "UTC"); setInterfaceDensity(settings.data.preferences.interfaceDensity); } }, [settings.data]);
  const save = trpc.settings.save.useMutation({ onSuccess: async () => { await utils.settings.get.invalidate(); toast.success("Workspace preferences saved."); }, onError: error => toast.error(error.message) });
  return <WorkspacePage eyebrow="Your workspace" title="Settings" description="Manage the preferences that shape this personal workspace and review the integrations available to it.">
    <section className="grid gap-5 lg:grid-cols-[1fr_0.9fr]"><div className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary/15 text-primary"><Settings2 className="size-5" /></div><div><h2 className="font-semibold tracking-tight">Workspace preferences</h2><p className="text-xs text-muted-foreground">Personal defaults for your AI workspace.</p></div></div>{previewPreferencesLoading || settings.isLoading ? <div role="status" className="mt-5 space-y-4"><div className="h-10 animate-pulse rounded-xl bg-muted" /><div className="h-10 animate-pulse rounded-xl bg-muted" /><div className="h-10 animate-pulse rounded-xl bg-muted" /></div> : previewPreferencesError || settings.isError ? <div role="alert" className="mt-5 rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">Workspace preferences could not be loaded. Refresh to try again.</div> : <><label className="mt-5 block text-xs font-semibold text-muted-foreground">Default model label<Input value={defaultModel} onChange={event => setDefaultModel(event.target.value)} className="mt-2 rounded-xl bg-background/60 text-foreground" /></label><label className="mt-4 block text-xs font-semibold text-muted-foreground">Time zone<Input value={timeZone} onChange={event => setTimeZone(event.target.value)} className="mt-2 rounded-xl bg-background/60 text-foreground" placeholder="UTC" /></label><label className="mt-4 block text-xs font-semibold text-muted-foreground">Interface density<select value={interfaceDensity} onChange={event => setInterfaceDensity(event.target.value as "comfortable" | "compact")} className="mt-2 h-10 w-full rounded-xl border border-input bg-background/60 px-3 text-sm text-foreground"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><Button disabled={save.isPending} onClick={() => save.mutate({ defaultModel, timeZone, interfaceDensity })} className="mt-5 gap-2 rounded-xl">{save.isPending ? <Loader2 className="size-4 animate-spin" /> : <Check className="size-4" />} Save preferences</Button>{save.isError && <p role="alert" className="mt-3 text-xs text-destructive">{save.error.message}</p>}</>}</div>
      <div className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-sky-400/10 text-sky-300"><PlugZap className="size-5" /></div><div><h2 className="font-semibold tracking-tight">Connected integrations</h2><p className="text-xs text-muted-foreground">Live app capability checks—credentials are never shown.</p></div></div><div className="mt-5 space-y-2.5">{settings.data?.integrations.map(integration => <div key={integration.name} className="flex items-center gap-3 rounded-xl border bg-background/35 p-3.5"><ShieldCheck className={`size-4 ${integration.state === "available" ? "text-emerald-300" : "text-amber-300"}`} /><div className="flex-1"><p className="text-sm font-semibold">{integration.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{integration.status}</p></div><span className={`size-2 rounded-full ${integration.state === "available" ? "bg-emerald-400" : "bg-amber-300"}`} /></div>)}{settings.isLoading && <div className="h-20 animate-pulse rounded-xl bg-muted" />}{settings.isError && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-xs text-destructive">Integration availability could not be loaded. Refresh to try again.</div>}</div><p className="mt-5 rounded-xl border border-border/60 bg-background/25 p-3 text-xs leading-5 text-muted-foreground">External connectors are kept separate from individual browser logins. This workspace reports only capabilities the app can verify without exposing secrets.</p></div>
    </section>
  </WorkspacePage>;
}
