import { WorkspacePage } from "@/components/WorkspacePage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { formatDate } from "@/lib/format";
import { trpc } from "@/lib/trpc";
import { Check, Loader2, Play, Plus, WandSparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const templates = [{ key: "summarize", label: "Summarize", note: "Turn long material into a clear brief." }, { key: "translate", label: "Translate", note: "Preserve meaning, tone, and structure." }, { key: "classify", label: "Classify", note: "Organize input into useful categories." }, { key: "generate", label: "Generate", note: "Create polished first drafts." }] as const;

export default function WorkflowAutomation() {
  const utils = trpc.useUtils(); const workflows = trpc.workflows.list.useQuery(); const [name, setName] = useState("New workflow"); const [template, setTemplate] = useState<(typeof templates)[number]["key"]>("summarize"); const [instructions, setInstructions] = useState("Produce a concise, practical result for my workspace."); const [sourceText, setSourceText] = useState(""); const [selectedWorkflow, setSelectedWorkflow] = useState<number | null>(null); const [result, setResult] = useState("");
  const create = trpc.workflows.create.useMutation({ onSuccess: async () => { await utils.workflows.list.invalidate(); toast.success("Workflow saved to your workspace."); }, onError: error => toast.error(error.message) });
  const execute = trpc.workflows.execute.useMutation({ onSuccess: async response => { setResult(response.output); await Promise.all([utils.taskHistory.list.invalidate(), utils.workspace.summary.invalidate()]); toast.success("Workflow completed."); }, onError: error => toast.error(error.message) });
  const selected = workflows.data?.find(workflow => workflow.id === selectedWorkflow);
  return <WorkspacePage eyebrow="Reusable intelligence" title="Workflow Automation" description="Build small, repeatable AI routines for the work you do often. Run them now or schedule them later.">
    <section className="grid gap-5 xl:grid-cols-[0.85fr_1.15fr]"><div className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-primary/15 text-primary"><Plus className="size-5" /></div><div><h2 className="font-semibold tracking-tight">Create a workflow</h2><p className="text-xs text-muted-foreground">Choose a template and refine it.</p></div></div><Input value={name} onChange={event => setName(event.target.value)} className="mt-5 rounded-xl bg-background/60" placeholder="Workflow name" /><div className="mt-3 grid grid-cols-2 gap-2">{templates.map(item => <button key={item.key} onClick={() => setTemplate(item.key)} className={`rounded-xl border p-3 text-left transition ${template === item.key ? "border-primary/60 bg-primary/10" : "border-border/80 bg-background/30 hover:bg-muted"}`}><p className="text-xs font-bold">{item.label}</p><p className="mt-1 text-[11px] leading-4 text-muted-foreground">{item.note}</p></button>)}</div><Textarea value={instructions} onChange={event => setInstructions(event.target.value)} className="mt-3 min-h-28 resize-none rounded-xl bg-background/60" placeholder="What should this workflow do?" /><Button className="mt-3 w-full gap-2 rounded-xl" disabled={create.isPending || name.trim().length < 2 || instructions.trim().length < 3} onClick={() => create.mutate({ name: name.trim(), template, instructions: instructions.trim() })}>{create.isPending ? <Loader2 className="size-4 animate-spin" /> : <Check className="size-4" />} Save workflow</Button>{create.isError && <p role="alert" className="mt-3 text-xs text-destructive">{create.error.message}</p>}</div>
      <div className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex items-center justify-between"><div><h2 className="font-semibold tracking-tight">Your workflows</h2><p className="mt-1 text-sm text-muted-foreground">Select a workflow to run it manually.</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-medium text-muted-foreground">{workflows.data?.length ?? 0} saved</span></div><div className="mt-5 space-y-2.5">{workflows.isLoading ? [0, 1, 2].map(index => <div key={index} className="h-20 animate-pulse rounded-xl bg-muted" />) : workflows.isError ? <div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-center text-xs text-destructive">Your workflows could not be loaded. Refresh to try again.</div> : workflows.data?.map(workflow => <button key={workflow.id} onClick={() => { setSelectedWorkflow(workflow.id); setSourceText(workflow.latestInput ?? ""); setResult(""); }} className={`w-full rounded-xl border p-4 text-left transition ${workflow.id === selectedWorkflow ? "border-primary/60 bg-primary/10" : "border-border/70 bg-background/25 hover:bg-muted/60"}`}><div className="flex items-center gap-3"><WandSparkles className="size-4 text-primary" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{workflow.name}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{workflow.template} · Updated {formatDate(workflow.updatedAt)}</p></div><span className={`size-2 rounded-full ${workflow.isEnabled ? "bg-emerald-400" : "bg-muted-foreground"}`} /></div></button>)}{!workflows.isLoading && !workflows.isError && !workflows.data?.length && <div className="rounded-xl border border-dashed p-10 text-center"><p className="text-sm font-medium">No workflows saved yet.</p><p className="mt-1 text-xs text-muted-foreground">Create your first repeatable AI routine on the left.</p></div>}</div></div>
    </section>{selected && <section className="rounded-2xl border bg-card/80 p-5 shadow-xl shadow-black/10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Manual run</p><h2 className="mt-1 text-xl font-semibold tracking-tight">{selected.name}</h2></div><Button disabled={execute.isPending || !sourceText.trim()} onClick={() => execute.mutate({ id: selected.id, sourceText: sourceText.trim() })} className="gap-2 rounded-xl">{execute.isPending ? <Loader2 className="size-4 animate-spin" /> : <Play className="size-4" />} Run workflow</Button></div><Textarea value={sourceText} onChange={event => setSourceText(event.target.value)} className="mt-4 min-h-36 resize-none rounded-xl bg-background/55" placeholder="Paste the text or instruction this workflow should process…" />{execute.isError && <p role="alert" className="mt-3 text-xs text-destructive">{execute.error.message}</p>}{result && <div className="mt-4 rounded-xl border bg-background/45 p-4"><p className="mb-2 text-xs font-bold uppercase tracking-[0.14em] text-muted-foreground">Latest output</p><p className="whitespace-pre-wrap text-sm leading-6">{result}</p></div>}</section>}
  </WorkspacePage>;
}
